name: Test Code

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 12.00
          cache: "npm"
       env:
          SUPER_SECRET: ${{ secrets.HASSAN }}
      - run: echo "$SUPER_SECRET"
